const EMAIL_VERIFICATION_CONFIRMATION_WAITING_IS_TRUE = 'EMAIL_VERIFICATION_CONFIRMATION_WAITING_IS_TRUE';
const EMAIL_VERIFICATION_CONFIRMATION_WAITING_IS_FALSE = 'EMAIL_VERIFICATION_CONFIRMATION_WAITING_IS_FALSE';

export const emailVerificationConfirmationWaitingIsTrue = {
    type: EMAIL_VERIFICATION_CONFIRMATION_WAITING_IS_TRUE,
};

export const emailVerificationConfirmationWaitingIsFalse = {
    type: EMAIL_VERIFICATION_CONFIRMATION_WAITING_IS_FALSE,
};
